# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				rabbit = true
				silverfish = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				mooshroom = true
				llama_spit = true
				glow_item_frame = false
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				ender_pearl = true
				zombie = true
				guardian = true
				illusioner = true
				eye_of_ender = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				boat = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				spider = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				vex = true
				piglin_brute = true
				ocelot = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				polar_bear = true
				hopper_minecart = true
				painting = true

			[light_sources.settings.entities.biomemakeover]
				rootling = true
				cowboy = true
				lightning_bug = true
				scuttler = true
				owl = true
				moth = true
				glowfish = true
				lightning_bug_alternate = true
				helmit_crab = true
				dragonfly = true
				decayed = true
				stone_golem = true
				adjudicator = true
				ghost = true
				blightbat = true
				mushroom_trader = true

			[light_sources.settings.entities.fishofthieves]
				devilfish = true
				splashtail = true
				stormfish = true
				ancientscale = true
				wrecker = true
				wildsplash = true
				plentifin = true
				islehopper = true
				pondie = true

			[light_sources.settings.entities.hookshot]
				hookshot = true

			[light_sources.settings.entities.lovely_snails]
				snail = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.immersive_portals]
				nether_portal_new = true
				end_portal = true
				loading_indicator = true

			[light_sources.settings.entities.mbembe]
				dodo = true
				mokele = true

			[light_sources.settings.entities.promenade]
				sunken_skeleton = true
				duck = true
				lush_creeper = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				flying_pig = true
				chair = true
				hydrogen_jellyfish = true
				skull = true
				jungle_skeleton = true
				naga = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				gyrodyne = true
				biplane = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				shadow_walker = true
				cubozoa = true
				end_slime = true
				silk_moth = true
				end_fish = true

			[light_sources.settings.entities.portalcubed]
				portal_placeholder = true
				experimental_portal = true

			[light_sources.settings.entities.mimic]
				mimic = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				moobloom = true
				mauler = true
				iceologer = true

			[light_sources.settings.entities.wilderwild]
				firefly = true
				jellyfish = true

